title: Diego Santamaria
description: Senior Software Engineer
url: https://diego-santamaria.github.io

lang: en
author: Diego Santamaria

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
