title: Diego Santamaria
description: Senior Software Engineer
url: https://diego-santamaria.github.io

lang: en
author: Diego Santamaria

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - README.md
